# Accuracy : 0.9691, Precision : 0.8625, Recall : 0.8407, F-score : 0.8515
python -u run.py \
  --task_name anomaly_detection \
  --is_training 1 \
  --root_path ./dataset/MSL \
  --model_id MSL \
  --model LoGix \
  --data MSL \
  --features M \
  --seq_len 100 \
  --pred_len 0 \
  --d_model 768 \
  --d_ff 768 \
  --patch_size 1 \
  --stride 1 \
  --enc_in 55 \
  --c_out 55 \
  --anomaly_ratio 2 \
  --batch_size 128 \
  --learning_rate 0.0001 \
  --depth 4 \
  --dropout 0.3 \
  --num_scales 5 \
  --train_epochs 10